# Generated by Django 6.0.1 on 2026-02-18 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_address_alter_userprofile_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalUpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_type', models.CharField(choices=[('interior_designer', 'Interior Designer'), ('exterior_designer', 'Exterior Designer'), ('architect', 'Architect'), ('worker', 'Worker'), ('contractor', 'Contractor')], max_length=20)),
                ('bio', models.TextField(help_text='Tell us about your professional experience')),
                ('experience_years', models.IntegerField(default=0, help_text='Years of experience')),
                ('phone', models.CharField(help_text='Professional contact number', max_length=15)),
                ('address', models.TextField(help_text='Business/professional address')),
                ('reason', models.TextField(help_text='Why do you want to become a professional?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin review notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
