# Generated by Django 6.0.1 on 2026-04-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Notes from admin when accepting/rejecting', null=True),
        ),
    ]
